graph TD
    1005["CCP 1005"] --> 1013["CCP 1013"]
    1011["CCP 1011"] --> 1010_6["CCP 1010.6"]
    1013["CCP 1013"] --> 1010_6["CCP 1010.6"]
    1013["CCP 1013"] --> 1010["CCP 1010"]
    1094_5["CCP 1094.5"] --> 1010["CCP 1010"]
    1094_6["CCP 1094.6"] --> 1094_5["CCP 1094.5"]
    1094_6["CCP 1094.6"] --> 1013["CCP 1013"]
    128_7["CCP 128.7"] --> 1010["CCP 1010"]
    128_7["CCP 128.7"] --> 1010["CCP 1010"]
    411_35["CCP 411.35"] --> 430_10["CCP 430.10"]
    425_11["CCP 425.11"] --> 1010["CCP 1010"]
    430_10["CCP 430.10"] --> 430_30["CCP 430.30"]
    430_10["CCP 430.10"] --> 411_35["CCP 411.35"]
    430_20["CCP 430.20"] --> 430_30["CCP 430.30"]
    430_41["CCP 430.41"] --> 472["CCP 472"]
    436["CCP 436"] --> 435["CCP 435"]
    438["CCP 438"] --> 436["CCP 436"]
    437c["CCP 437c"] --> 437["CCP 437"]
    437c["CCP 437c"] --> 1005["CCP 1005"]
    527["CCP 527"] --> 1005["CCP 1005"]

    classDef Jurisdiction&Service fill:#ff9999
    class 410_10 Jurisdiction&Service
    classDef Jurisdiction&Service fill:#ff9999
    class 410_42 Jurisdiction&Service
    classDef Jurisdiction&Service fill:#ff9999
    class 410_70 Jurisdiction&Service
    classDef Jurisdiction&Service fill:#ff9999
    class 411_10 Jurisdiction&Service
    classDef Jurisdiction&Service fill:#ff9999
    class 411_35 Jurisdiction&Service
    classDef Jurisdiction&Service fill:#ff9999
    class 412_30 Jurisdiction&Service
    classDef Jurisdiction&Service fill:#ff9999
    class 413_40 Jurisdiction&Service
    classDef Jurisdiction&Service fill:#ff9999
    class 414_10 Jurisdiction&Service
    classDef Jurisdiction&Service fill:#ff9999
    class 415_95 Jurisdiction&Service
    classDef Jurisdiction&Service fill:#ff9999
    class 416_90 Jurisdiction&Service
    classDef Pleadings fill:#99ff99
    class 438 Pleadings
    classDef Pleadings fill:#99ff99
    class 473 Pleadings
    classDef Service&Notice fill:#ffff99
    class 1003 Service&Notice
    classDef Service&Notice fill:#ffff99
    class 1005 Service&Notice
    classDef Service&Notice fill:#ffff99
    class 1010_6 Service&Notice
    classDef Service&Notice fill:#ffff99
    class 1010 Service&Notice
    classDef Service&Notice fill:#ffff99
    class 1011 Service&Notice
    classDef Service&Notice fill:#ffff99
    class 1012 Service&Notice
    classDef Service&Notice fill:#ffff99
    class 1013 Service&Notice
    classDef Service&Notice fill:#ffff99
    class 1014 Service&Notice
