graph TD

    classDef Jurisdiction&Service fill:#ff9999
    class 410_10 Jurisdiction&Service
    classDef Jurisdiction&Service fill:#ff9999
    class 410_10 Jurisdiction&Service
    classDef Jurisdiction&Service fill:#ff9999
    class 410_42 Jurisdiction&Service
    classDef Jurisdiction&Service fill:#ff9999
    class 410_42 Jurisdiction&Service
    classDef Jurisdiction&Service fill:#ff9999
    class 410_70 Jurisdiction&Service
    classDef Jurisdiction&Service fill:#ff9999
    class 410_70 Jurisdiction&Service
    classDef Jurisdiction&Service fill:#ff9999
    class 411_35 Jurisdiction&Service
    classDef Jurisdiction&Service fill:#ff9999
    class 411_35 Jurisdiction&Service
    classDef Jurisdiction&Service fill:#ff9999
    class 412_30 Jurisdiction&Service
    classDef Jurisdiction&Service fill:#ff9999
    class 412_30 Jurisdiction&Service
    classDef Pleadings fill:#99ff99
    class 420 Pleadings
    classDef Pleadings fill:#99ff99
    class 420 Pleadings
    classDef Pleadings fill:#99ff99
    class 421 Pleadings
    classDef Pleadings fill:#99ff99
    class 421 Pleadings
    classDef Pleadings fill:#99ff99
    class 422_40 Pleadings
    classDef Pleadings fill:#99ff99
    class 422_40 Pleadings
    classDef Pleadings fill:#99ff99
    class 425_55 Pleadings
    classDef Pleadings fill:#99ff99
    class 425_55 Pleadings
    classDef Pleadings fill:#99ff99
    class 426_70 Pleadings
    classDef Pleadings fill:#99ff99
    class 426_70 Pleadings
    classDef Service&Notice fill:#ffff99
    class 1002_7 Service&Notice
    classDef Service&Notice fill:#ffff99
    class 1008 Service&Notice
